apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z1q2844sx-python
  janus-idp.io/tekton: z1q2844sx-python
  backstage.io/kubernetes-id: z1q2844sx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z1q2844sx-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
