apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z1q2844sx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z1q2844sx-python 
  name: z1q2844sx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: z1q2844sx-python 
